# Generated by Django 3.2.2 on 2022-06-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_auto_20220619_0313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-date']},
        ),
    ]
