# Generated by Django 3.2.2 on 2022-06-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_alter_neighbourhood_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='business',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
