# Generated by Django 3.2.2 on 2022-06-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0008_auto_20220619_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
